// Generated by EmDash on dev server start
// Do not edit manually

/// <reference types="emdash/locals" />

import type { ContentBylineCredit, PortableTextBlock } from "emdash";

export interface Page {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  content?: PortableTextBlock[];
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface Project {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  featured_image: { id: string; src?: string; alt?: string; width?: number; height?: number };
  client?: string;
  year?: string;
  summary?: string;
  content?: PortableTextBlock[];
  gallery?: unknown;
  url?: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

declare module "emdash" {
  interface EmDashCollections {
    pages: Page;
    projects: Project;
  }
}